// Resumos de módulo do Observatório (fecho de cada vista). v3: maiores, completos e estratégicos.
// Comercial & Desenvolvimento = SÓ produto/desenvolvimento (modelos, cores, materiais, preço, apostas).
// Marketing = campanhas, embaixadoras, collabs, manchetes/corporativo (M&A, expansão, faturamento) + Instagram.
// Cada resumo fecha com bloco "Movimento recomendado p/ Vessel" (ações concretas) + posição no tabuleiro de preço.
import fs from 'fs';
const env = {};
for (const l of fs.readFileSync(new URL('./.env', import.meta.url), 'utf8').split('\n')) {
  const m = l.match(/^([A-Z_]+)=(.*)$/); if (m) env[m[1]] = m[2].replace(/^["']|["']$/g, '');
}
const URL_SB = env.SUPABASE_URL, KEY = env.SUPABASE_SERVICE_KEY;
const RODADA = '2026-06-23';
const sbH = { apikey: KEY, Authorization: 'Bearer ' + KEY, 'Content-Type': 'application/json' };
async function rest(method, path, body) {
  const r = await fetch(URL_SB + '/rest/v1/' + path, { method, headers: { ...sbH, Prefer: 'return=representation' }, body: body ? JSON.stringify(body) : undefined });
  const t = await r.text(); if (!r.ok) throw new Error(method + ' ' + path + ' → ' + r.status + ' ' + t.slice(0, 200)); return t ? JSON.parse(t) : null;
}

// Tabuleiro de preço do painel (bolsas, ticket de campeãs) — usado como referência cruzada:
// Petite Jolie R$65–270 · Santa Lolla R$150–300 · Anacapri R$200–300 · Capodarte R$290–1.190 ·
// Jorge Bischoff R$499–1.399 · Luz da Lua R$500–1.500 · Dumond R$600–1.300 · Arezzo R$899–1.299 ·
// Schutz R$990–1.990 · Carmen Steffens R$1.000–1.700.

const S = {
'Anacapri': {
  com: { t: 'O DNA acessível: sintético, tiracolo e a customização como tese de produto',
    r: `Se a Anacapri fosse uma bolsa, seria uma **tiracolo de R$219,90 em cor neutra** — e isso não é defeito, é estratégia. A marca domina o **degrau de entrada** com um método quase industrial: poucos shapes, muitas cores, giro alto.\n\n## O que as campeãs revelam\nO best-seller é um leque enxuto, repetido à exaustão em **preto, marrom, cinza e branco**. A marca não dispersa portfólio — ela **verticaliza cor sobre um mesmo molde**:\n- **Tote Média Sachel** — R$289,90\n- **Tiracolo Estruturada Média** — R$259,90\n- **Tiracolo Slim Média** — R$219,90\n- **Tiracolo Matelassê Zig Zag** — R$199,90 *(o piso)*\n\nFaixa apertadíssima de **R$199 a R$299**, base **sintética/têxtil**. Esse desenho dá duas vantagens: **escala de produção** (poucos moldes) e **folga de margem para promover** quando precisar girar estoque.\n\n## A aposta que aponta o futuro\nO sneaker **V6 "Brasil Core"** (atacadores coloridos, pins de estrela removíveis) entrega a verdadeira tese de desenvolvimento da casa: **customização como linguagem**. A bolsa ainda não fala isso, mas o calçado já está testando o terreno — e personalização é um caminho barato de diferenciar um produto sintético.\n\n## Onde isso se encaixa no tabuleiro\nNo painel, a Anacapri ocupa o **degrau imediatamente acima da Santa Lolla e ao lado dela em preço** (R$200–300), mas com **menos construção de marca/ícone**. É volume puro, sem totem. Para a Vessel — que disputa essa mesma faixa — a Anacapri é a **referência de "básico eficiente"**, não de desejo.\n\n## Movimento recomendado p/ Vessel\n- **Não brigar preço:** com poucos moldes e base sintética, a Anacapri sempre vence o leilão de desconto. Perder margem aqui é perder a guerra.\n- **Subir o acabamento percebido** (forro, ferragem, costura aparente) sobre o mesmo ticket: ser o "teto" do degrau de entrada, não mais um competidor do piso.\n- **Roubar a tese de customização** antes que ela chegue às bolsas: uma alça intercambiável ou um charm assinado diferencia sem inflar custo.\n\n**Veredito competitivo:** ameaça de **volume e preço**, não de desejo. Combater com **percepção**, nunca com tabela.`,
    tags: ['R$199–299', 'Sintético/têxtil', 'Poucos moldes, muitas cores', 'Customização (V6)', 'Piso de mercado', 'Folga p/ promo', 'Ameaça: volume'] },
  mkt: { t: 'Sem rosto famoso, com muita gente: o jogo de comunidade dentro da Azzas',
    r: `A Anacapri faz uma escolha de comunicação **rara e inteligente**: em vez de comprar uma celebridade cara, ela **compra participação do público** — e isso escala melhor do que parece.\n\n## A mecânica de marca\n- **Collab com a Sundown** (protetor solar): um **co-branding de comportamento** ("curtir o sol com conforto e segurança"), não de produto. A bolsa entra num *contexto de vida*, não num anúncio.\n- **Desafio no TikTok** (#AnacapriSundown / #VemProSol): premiou os vídeos mais criativos do público. **UGC puro, sem embaixadora** — a marca terceiriza o conteúdo para a audiência e ainda colhe alcance orgânico.\n- Campanha **"Ser brasileira é…"** (Mônica Martelli) + estética **Brasil Core**: afeto nacional + Geração Z.\n\n## O bastidor estratégico\nA Anacapri joga dentro da **Azzas 2154** — holding que fechou 2025 com **lucro de R$770,7 mi (+30%)** e receita de **R$14,7 bi**. A marca vem de performance fraca, mas o CFO sinalizou **recuperação**. Leitura prática para nós: há **caixa por trás** e **pressão por retomada** — combinação que historicamente vira **mais promoção, mais volume e campanhas de fôlego** nos trimestres seguintes. Esperar uma Anacapri **mais agressiva**, não menos.\n\n## Onde está a brecha\nO ponto cego é o **produto**: a comunicação fala de "vibe", desafio e brasilidade, mas **quase nunca explica a bolsa** — modelo, material, por que aquela peça. É desejo de contexto, não de objeto.\n\n## Movimento recomendado p/ Vessel\n- **Ocupar o vazio de "conteúdo que explica o produto":** vídeos curtos de material, costura, porquê do shape. Onde a Anacapri faz "vibe", a Vessel faz **autoridade**.\n- **Testar UGC de baixo custo** (a tática que mais deu certo para ela): um desafio/repost com clientes reais rende alcance sem cachê de influencer.\n- **Vigiar o calendário promocional da Azzas:** se a Anacapri abrir desconto pesado, não revidar no preço — revidar com **lançamento/ícone**.\n\n**Veredito competitivo:** comunicação **forte em alcance, fraca em produto**. A brecha é didática — e barata de ocupar.`,
    tags: ['Collab Sundown', '#AnacapriSundown (UGC)', 'Mônica Martelli', 'Azzas +30% (caixa)', 'Esperar + agressiva', 'Gap: explica produto', 'Brasil Core'] },
},
'Arezzo&Co': {
  com: { t: 'Couro, croco e ferragem dourada: a gramática do desejo premium',
    r: `A Arezzo desenvolve bolsa como quem **escreve manifesto**: cada campeã repete três palavras — **couro, animal print, dourado** — até virarem sinônimo da marca.\n\n## O que as campeãs revelam\nTicket altíssimo (**4–5× a Santa Lolla**), tudo em couro, com a ferragem dourada como assinatura inegociável:\n- **Hobo Couro Multicolorida Grande** — R$1.199,90 *(topo)*\n- **Tiracolo Croco c/ Corrente** (marrom / animal print) — R$999,90\n- **Hobo Couro c/ Corrente Dourada** — R$999,90\n- **Shoulder Couro Média** — R$899,90 *(porta de entrada do premium)*\n\nA faixa **R$899–R$1.299** não é preço, é **posicionamento**: a bolsa é objeto aspiracional, não utilitário. E repare na **disciplina** — pouquíssimos shapes, um material, um detalhe-assinatura, repetidos com convicção. É o oposto da pulverização.\n\n## A aposta de desenvolvimento\nO **detalhe metálico** (corrente, fecho) e a **textura croco/animal print** são o vocabulário de valor. Não há experimento de material — o couro é dogma. A Arezzo desenvolve **em torno de um símbolo de status**, e a consistência é o que faz o status grudar.\n\n## Onde isso se encaixa no tabuleiro\nNo painel, a Arezzo ancora o **topo aspiracional** ao lado de Schutz e Carmen Steffens (todas acima de R$900). Está a **3–6× o ticket da Vessel** — ou seja, **não é concorrente direto de preço**, é concorrente de **referência de desejo**: é a marca que define o que "bolsa cara desejável" significa na cabeça da cliente.\n\n## Movimento recomendado p/ Vessel\n- **Não imitar o ticket, imitar a disciplina:** escolher **um detalhe-assinatura** (a "ferragem dourada" da Vessel) e repetir até virar reconhecível. Foco vence variedade.\n- **Capturar a cliente "aspiracional sem orçamento":** quem deseja Arezzo mas não paga R$1.000 é exatamente o público que a Vessel pode converter com **couro/ecocouro bem-acabado a 1/3 do preço**.\n- **Estudar a estética (clean, produto no centro)** para o nosso conteúdo premium — a Arezzo é aula de fotografia de produto.\n\n**Veredito competitivo:** não é briga de preço, é **briga de imaginário**. A Arezzo é a régua do desejo — usá-la como **âncora de comparação** ("o couro Arezzo custa 4×") é argumento de venda.`,
    tags: ['Couro R$899–1.299', 'Croco + animal print', 'Ferragem dourada (assinatura)', 'Ticket 4–5× SL', 'Disciplina de shape', 'Topo aspiracional', 'Âncora de desejo'] },
  mkt: { t: 'De Hollywood a Higienópolis: quando o sapato vira comportamento (e o grupo, tabuleiro)',
    r: `A Arezzo joga marketing em **duas pontas ao mesmo tempo** — e é essa amplitude que a torna difícil de bater com orçamento pequeno.\n\n## A ponta aspiracional\n**Sarah Jessica Parker** — a eterna Carrie Bradshaw, maior ícone de sapatos da cultura pop — assina o Inverno 2026 sob *"Obcecada por sapatos, desde sempre"*. Direção clean, retrato de estúdio, produto no centro. A atriz vira **ponte cultural**: traduz calçado/bolsa como **identidade e desejo**, não como compra. É marketing de **significado**, não de oferta.\n\n## A ponta jovem\nA **collab Arezzo + FILA** (tênis, bolsas, acessórios com pegada esportiva urbana) busca o público que a SJP não alcança. A marca cobre **da maturidade glamourosa ao streetwear** — duas tribos, uma marca.\n\n## O que viralizou\n- Inverno "do seu jeito" (botas + bolsas) — **718❤**\n- Collab **FILA** — **528❤**\n- **Vanity bag** essencialista — **386❤ / 43💬** *(maior conversa — produto pequeno e prático gera diálogo)*\n\n## O bastidor estratégico\nA **Azzas contratou o Morgan Stanley** para avaliar alternativas para a **Farm Rio** ("destravar valor", possível venda internacional), em meio à disputa pública **Birman × Jatahy**. É um **grupo reorganizando portfólio** — vale vigiar se a atenção/investimento migra da Arezzo para resolver a Farm. Distração no topo costuma abrir espaço embaixo.\n\n## Movimento recomendado p/ Vessel\n- **Não competir em verba — competir em intimidade:** a Arezzo vende "mundo" para milhões; a Vessel pode vender **relação** para milhares. Nicho profundo é o que marca grande não consegue.\n- **Adotar a estética "produto no centro"** nos posts premium: menos ruído, mais bolsa bem fotografada.\n- **Aproveitar a janela de distração corporativa:** enquanto o grupo olha para a Farm, é hora de **ganhar share de atenção** com consistência.\n\n**Veredito competitivo:** marketing de **classe mundial e dois públicos** — imbatível no alcance. A defesa da Vessel é a **profundidade**, não a largura.`,
    tags: ['SJP embaixadora', 'Collab FILA', 'Dual público', 'Vanity 386❤/43💬', 'Morgan Stanley/Farm', 'Janela de distração', 'Defesa: nicho'] },
},
'Capodarte': {
  com: { t: 'Monograma, tote e a virada premium: o produto que sobe de patamar',
    r: `A Capodarte está **literalmente redesenhando o que é** — e a bolsa é a linha de frente dessa virada de patamar.\n\n## O que as campeãs revelam\nO **monograma** é a estrela e o **tote** é o shape-mãe, numa faixa larga (**R$290 a R$1.190**) que cobre da entrada ao premium num mesmo catálogo:\n- **Tote Couro Preta** — R$1.190 *(topo)*\n- **Tote Monograma** (preta / marrom café) — R$690\n- **Shopper Monograma** (grande / média) — R$650 / R$550\n- **Pietra Shoulder Bag** — R$290 *(isca de entrada)*\n\nEsse **leque de preço amplo** é uma decisão estratégica: a marca usa o monograma barato (R$290) como porta e o couro liso (R$1.190) como aspiração — **mesma identidade visual, três faixas de bolso**.\n\n## As novidades confirmam o rumo\nA leva nova aposta em **baguete de couro** (R$890) em cores de inverno (mogno, turmalina) e **doctor bag monograma** — shapes mais estruturados e "assináveis". A cápsula **Tressê Signature** (35 anos, tramas manuais, couros exóticos) puxa o teto e dá pedigree.\n\n## Onde isso se encaixa no tabuleiro\nA Capodarte é a **ponte do painel**: começa onde a Vessel/Santa Lolla atuam (R$290) e sobe até o território da Jorge Bischoff/Dumond. É a concorrente que **mais "encosta de baixo e puxa para cima"** — perigosa porque pega o cliente da Vessel e o leva ao premium dentro da mesma marca.\n\n## Movimento recomendado p/ Vessel\n- **Atenção máxima ao degrau R$290–500:** é a fronteira onde a Capodarte rouba o cliente da Vessel oferecendo "monograma de marca" a preço de entrada.\n- **Criar um código visual proprietário** (estampa, ferragem, forro): a lição da Capodarte é que **assinatura visível sustenta preço** e permite escalar faixas sem perder reconhecimento.\n- **Monitorar a expansão física** (50→200 lojas): quando uma loja Capodarte abrir no entorno de um ponto da Vessel, esperar pressão no fluxo.\n\n**Veredito competitivo:** **a mais perigosa para o crescimento da Vessel** — não pelo topo, mas pela **base que ela sobe**.`,
    tags: ['Monograma assinatura', 'Tote shape-mãe', 'R$290–1.190 (leque amplo)', 'Baguete couro (novo)', 'Tressê 35 anos', 'Encosta de baixo', 'Mais perigosa'] },
  mkt: { t: 'A aula de conteúdo que converte: o "match" bota + bolsa com SKU e preço',
    r: `Se há **um playbook de Instagram para copiar inteiro** neste painel, é o da Capodarte. Ela transformou o feed numa **vitrine que vende**, não numa galeria que inspira.\n\n## A mecânica\nQuase todo post é um **"match"** — um look montado (bota + bolsa, às vezes + sapatilha) — com **referência e preço escritos na legenda**. Não é "inspiração", é **caminho de compra encurtado**: a pessoa vê o look, lê o preço e já sabe o que pedir. O fio condutor é o **marrom cacao** do Inverno 26 e texturas autorais (**enguia, pony**).\n\n## O que viralizou\n- Trio **enguia cacao** (bota+bolsa+sapatilha) — **1.407❤** *(o maior engajamento de TODO o painel)*\n- Bolsa Olívia + bota **pony** — **353❤**\n- Shoulder bag fecho ímã — **319❤**\n- Bota slouch enguia + Olívia Mini — **284❤**\n\nO dado mais importante: os campeões **sempre** trazem SKU + preço. A audiência **recompensa a clareza comercial** — o oposto do mito de que "preço no post espanta".\n\n## O bastidor estratégico\nRebranding **"4Cs"** (premium) após a compra pela **Di Santinni (R$36 mi)** e expansão agressiva (**50 → 200 lojas até 2030**, multimarcas 500 → 1.000). A marca constrói **presença física e digital em paralelo** — e o conteúdo de produto é o motor de descoberta dessa máquina.\n\n## Movimento recomendado p/ Vessel\n- **Adotar a gramática do "duo" já:** look montado + SKU + preço. É a tática de **maior ROI e mais fácil** deste relatório inteiro — não custa verba, custa disciplina de legenda.\n- **Padronizar o "preço na arte":** transformar em regra do conteúdo, não exceção.\n- **Ancorar cada post numa cor/textura da estação** (como o "cacao"): dá coesão e faz a coleção parecer maior do que é.\n\n**Veredito competitivo:** **a melhor referência tática do painel.** Não dá para copiar o couro da Arezzo, mas dá para copiar o feed da Capodarte **esta semana**.`,
    tags: ['Match bota+bolsa', 'SKU+preço sempre', '1.407❤ (topo do painel)', 'Marrom cacao', 'Rebranding 4Cs', '50→200 lojas', 'Maior ROI tático'] },
},
'Carmen Steffens': {
  com: { t: 'Couro, metais aplicados e matelassê: o premium artesanal de R$1.700',
    r: `A Carmen Steffens desenvolve bolsa como **peça de joalheria** — na cabeça dela o metal não é detalhe, é o protagonista.\n\n## O que as campeãs revelam\nFaixa **premium pura (R$999 a R$1.699)**, com o couro e a **aplicação de metais** no centro:\n- **Couro c/ Aplicação de Metais** (preta / bege / manteiga) — R$1.699,90 *(topo)*\n- **Shopping Preta/Ouro** — R$1.699,90\n- **Couro Estruturada** (manteiga / verde / pitanga) — R$1.499,90\n- **Matelassê c/ Fivela** — R$999,90 *(porta de entrada)*\n\nO dado mais interessante é a **cartela de cor ousada** — **verde, pitanga, manteiga**, raríssimas no premium, que costuma jogar seguro no preto/marrom. Aqui a **cor é o diferencial**, e isso é uma escolha de desenvolvimento corajosa.\n\n## A aposta de desenvolvimento\n**Matelassê** + **metal aplicado** + **personalização** (chaveiro com iniciais) = produto que pede para ser percebido como exclusivo e individual. A marca desenvolve **exclusividade percebida** — e cobra por ela.\n\n## Onde isso se encaixa no tabuleiro\nÉ o **topo absoluto de ticket do painel** (junto com a Schutz). A ~5–7× o preço da Vessel, não é concorrente de bolso. Mas serve de **laboratório de tendência de cor**: o que a CS ousa no premium hoje (verde, pitanga) costuma **descer de preço** e virar mainstream em 1–2 estações.\n\n## Movimento recomendado p/ Vessel\n- **Roubar a coragem cromática, não o ticket:** uma cartela ousada (um verde, um vinho, um terroso "diferente") diferencia a Vessel num mar de preto/marrom — desde que o acabamento sustente.\n- **Antecipar tendência de cor:** usar a CS como **radar** — o que ela lança em couro premium, a Vessel pode oferecer em ecocouro/sintético acessível antes do mercado massificar.\n- **Testar personalização barata** (charm/iniciais): a CS prova que "meu" vale mais que "bonito".\n\n**Veredito competitivo:** **não é ameaça de preço, é fonte de tendência.** Tratar como radar de cor e acabamento.`,
    tags: ['R$999–1.699 (premium)', 'Metal aplicado', 'Matelassê', 'Cartela ousada (verde/pitanga)', 'Personalização', 'Radar de tendência', 'Não é ameaça'] },
  mkt: { t: 'Editorial sofisticado por fora, máquina de CRM por dentro',
    r: `A Carmen Steffens tem **duas caras** — uma linda e uma poderosa — e a poderosa, a que realmente vende, **não aparece no feed**.\n\n## A cara editorial (Instagram)\nConteúdo **#Winter26 #Signature**, refinadíssimo: foco no **detalhe** (aplicação metálica em flor, croco personalizável), retorno da **bowling bag**, clutches metálicas, tom de *"arte em forma de composição"*. **Lindo — mas contemplativo:** não aparecem números de viralização altos no recorte e o conteúdo **fala pouquíssimo de preço/compra**. É desejo sem chamada para ação — exatamente o erro oposto ao da Capodarte.\n\n## A campanha\n**Andressa Suita** estrela a **Lumière d'Été**, reposicionando a marca para algo **mais contemporâneo e parisiense** (champagne, verde menta, coral). Movimento de imagem, mais que de venda.\n\n## A cara poderosa (corporativo)\nAqui mora a vantagem real: com **560 lojas em 19 países**, a CS cresceu **+20% em 2024 (~R$70 mi)** ao adotar **CRM e giftback** — capturando comportamento de cliente e atacando a **recorrência**, seu gargalo histórico. Mira **40 países até 2035** (Dubai, China, Índia). A marca descobriu que **dado vende mais que post**.\n\n## Onde está a brecha\nNo **conteúdo**: bonito e **fácil de superar em conversão** (sem CTA, sem preço). A CS deixa engajamento e venda na mesa por excesso de sofisticação.\n\n## Movimento recomendado p/ Vessel\n- **Combinar o melhor das duas:** a **estética CS** + a **clareza comercial da Capodarte** = desejo COM caminho de compra. Esse é o ponto ideal de conteúdo.\n- **Levar o CRM a sério:** a verdadeira vantagem da CS é **recorrência**, não feed. Vale comparar/estruturar nosso programa de base (recompra, giftback simples).\n- **Atacar onde ela é fraca:** conteúdo com preço e CTA conquista o cliente que admira o estilo CS mas não acha "como comprar".\n\n**Veredito competitivo:** **forte na retaguarda (CRM), frágil na vitrine digital.** Superável no conteúdo, respeitável na recorrência.`,
    tags: ['#Signature Winter26', 'Desejo sem CTA', 'Andressa Suita', 'CRM + giftback (+20%)', '560 lojas / 40 países', 'Dado > post', 'Superável no conteúdo'] },
},
'Dumond': {
  com: { t: 'Couro estruturado e matelassê: a herança Paquetá traduzida em produto',
    r: `A Dumond desenvolve em cima de um ativo que poucas têm: **80 anos de couro** (Grupo Paquetá, 1945). O produto é, de longe, **o melhor argumento da marca**.\n\n## O que as campeãs revelam\nO **matelassê de couro** é a coqueluche, num ticket intermediário-alto (**R$599 a R$1.299**):\n- **Tote Matelassê Couro** (vermelho / preto / caramelo) — R$1.299,90 *(topo)*\n- **Tiracolo Matelassê Couro** (mesmas cores) — R$999,90\n- **Shopper Camurça c/ Necessaire e Tachas** — R$899,90\n- **Duo Alças Meia Lua Camurça** — R$599,90 *(entrada)*\n\nDois dados saltam: o **vermelho** entre as campeãs (cor de risco que está vendendo — sinal de cliente disposta a ousar) e a presença de **camurça** ao lado do couro liso, ampliando o repertório de textura.\n\n## As novidades confirmam\nO **Inverno 2026** dobrou a aposta em **couro estruturado**, botas e paleta amadeirada (whisky, pinhão, cacau), reforçando **tecelagem manual e acabamento** como discurso.\n\n## Onde isso se encaixa no tabuleiro\nA Dumond entrega **couro genuíno na faixa R$600–1.300** — ou seja, **couro de verdade pelo preço de sintético premium de concorrente**. Ela é a marca que mais **espreme a relação valor/material**: por R$999 você leva matelassê de couro que, na Arezzo, custaria o dobro. Para a Vessel, é a **concorrente mais perigosa no quesito "couro com história a preço civil"**.\n\n## Movimento recomendado p/ Vessel\n- **Mapear o matelassê vermelho/caramelo:** é para onde o gosto está indo no couro acessível. Ter resposta direta a esses shapes.\n- **Não disputar a herança (não temos 80 anos), disputar o presente:** acabamento atual, cor da estação, drop frequente — terreno onde uma marca ágil bate uma tradicional.\n- **Explorar a fraqueza dela (ver Marketing):** produto superior + presença digital muda = brecha. Onde a Dumond cala, a Vessel fala.\n\n**Veredito competitivo:** **maior ameaça de produto** na faixa de couro acessível. A boa notícia está fora do produto.`,
    tags: ['Matelassê couro', 'R$599–1.299', 'Vermelho vende', 'Camurça + couro', 'Grupo Paquetá (1945)', 'Couro a preço civil', 'Ameaça de produto'] },
  mkt: { t: 'O benchmark invertido: produto forte, presença digital quase muda',
    r: `Este é, talvez, **o caso mais acionável de todo o relatório** — porque ensina pelo erro e aponta uma brecha que a Vessel pode ocupar **sem precisar de produto melhor**.\n\n## O descompasso\nA Dumond tem **um dos melhores produtos** do painel (couro, herança, matelassê desejável) e, no Instagram, **silêncio quase total**: no recorte, **um único post relevante** (matelassê, correntes) com **apenas 25❤** — engajamento **dezenas de vezes menor** que pares de ticket parecido (Jorge Bischoff fez **1.019**, Luz da Lua **1.068** com produto comparável). A diferença não é de catálogo, é de **presença**.\n\n## O que isso significa\nProduto excelente **não vira marca sozinho**. Num mundo em que a descoberta acontece no feed, a Dumond está **deixando share de atenção na mesa** todo dia. A herança Paquetá, o couro, a "mulher independente" — tudo isso está **escrito no site, mas não está sendo contado onde o público jovem decide**.\n\n## Onde está a brecha (e por que importa)\nMercado é um jogo de **atenção × desejo**. A Dumond tem desejo latente (produto) e **zero ativação de atenção**. Esse é o tipo de concorrente mais fácil de superar: **não se compete com o produto dela, compete-se com a presença que ela não tem.**\n\n## Movimento recomendado p/ Vessel\n- **Consistência como arma:** publicar com frequência e qualidade ocupa o espaço mental que a Dumond abandona — mesmo com produto de ticket parecido.\n- **Contar a história que ela não conta:** "couro com origem", processo, acabamento. A Vessel pode narrar valor enquanto a Dumond se cala.\n- **Mirar o cliente órfão da Dumond:** quem ama o produto dela mas nunca a vê no feed é cliente **disponível** — basta aparecer.\n\n**Veredito competitivo:** **produto ≫ presença.** O caso onde a vitória vem de **estar presente**, não de ser melhor.`,
    tags: ['IG mudo (25❤)', 'Produto ≫ presença', 'JB 1.019 vs Dumond 25', 'Share de atenção na mesa', 'Brecha de voz', 'Cliente órfão', 'Caso mais acionável'] },
},
'Jorge Bischoff': {
  com: { t: 'Couro exótico e baguete: o desenvolvimento que mira o "lifestyle de luxo"',
    r: `A Jorge Bischoff desenvolve bolsa com **ambição de grife internacional** — e o portfólio entrega isso na textura, não no preço.\n\n## O que as campeãs revelam\nFaixa **intermediária-premium (R$499 a R$1.399)**, com forte apetite por **couros nobres e exóticos**:\n- **Saco Preto Couro** — R$1.399 *(topo)*\n- **Transversal Selvagem Café Pelo** / **Infinita Tabaco** — R$1.299\n- **Infinita Monograma Florença** — R$999\n- **Belt Bag Monograma** — R$799\n- **Transversal Monograma** — R$499 *(entrada)*\n\nDois traços de desenvolvimento: **variedade de shape** (baguete, clutch, hobo, belt bag, saco) e **obsessão por textura** (croco, avestruz, pelo). A JB prioriza **repertório de pele** sobre repetição de molde — estratégia oposta à da Anacapri.\n\n## As novidades confirmam\nA leva nova traz **Say Yes** (linha noiva, off-white acetinado), a estampa autoral **Selvagem** batizada de "Bambi Core" e muito **croco** — até **R$1.599** (tote couro algodão). O monograma JB ancora o reconhecimento em meio à variedade.\n\n## Onde isso se encaixa no tabuleiro\nA JB ocupa o **intermediário-alto** (R$499–1.399), sobrepondo-se à Luz da Lua e cruzando com a Dumond. Com **entrada em R$499**, ela toca o teto da faixa da Vessel — é o **degrau imediatamente acima** que o cliente da Vessel pode almejar. Concorrente de aspiração, não de base.\n\n## Movimento recomendado p/ Vessel\n- **Usar textura como diferencial barato:** pelo, croco e avestruz criam percepção de luxo sem necessariamente dobrar custo (existe ecocouro texturizado convincente). É a lição de produto mais aplicável da JB.\n- **Batizar as linhas** (como "Say Yes", "Selvagem"): nome dá narrativa e exclusividade ao mesmo molde.\n- **Atacar a entrada (R$499):** oferecer "cara de JB" por menos é converter quem deseja a marca mas trava no preço.\n\n**Veredito competitivo:** **concorrente de aspiração** — define o que o cliente da Vessel quer "subir". Capturar essa subida é a oportunidade.`,
    tags: ['R$499–1.399', 'Couro exótico (pelo/avestruz/croco)', 'Variedade de shape', 'Say Yes / Bambi Core', 'Monograma JB', 'Linhas nomeadas', 'Aspiração'] },
  mkt: { t: 'Coleção que vira história e o conteúdo de ocasião que converte',
    r: `A Jorge Bischoff faz o que a Capodarte faz (SKU+preço no post), mas adiciona uma camada que multiplica o resultado: **narrativa**.\n\n## A mecânica\nO feed combina **narrativa de coleção** ("Bambi Core", "First Look Summer 27" — nomes próprios que viram tendência *interna* e dão sensação de movimento) com **conteúdo de ocasião** (noiva, Dia dos Namorados), sempre com **referência e preço** na legenda. É storytelling **funcional**: cada história termina num produto comprável.\n\n## O que viralizou\n- Bolsa de noiva **#SayYes** — **1.019❤ / 39💬** *(líder)*\n- **Bambi Core** (estampa Selvagem) — **522❤**\n- Bolsa Baú Namorados — **417❤ / 35💬**\n- Wishlist Namorados (look completo) — **365❤**\n\nO padrão é cristalino: **momento afetivo + produto nomeado + preço = engajamento alto e estável.** A JB não depende de viral de sorte; ela **fabrica relevância em cima do calendário**.\n\n## O bastidor estratégico\n**140+ lojas em 60 países**, ~**2 mi de itens/ano**, agora expandindo para **eyewear** (solar) e **quiosques premium** (+20 lojas), sob "Infinitas Oportunidades". A marca vira **plataforma de lifestyle** — vende um mundo, e o conteúdo amarra esse mundo.\n\n## Movimento recomendado p/ Vessel\n- **Roubar duas táticas prontas:** (1) **batizar tendências próprias** (cria exclusividade percebida de graça) e (2) **ancorar conteúdo em datas/ocasiões** com o produto certo e o preço à mão.\n- **Montar um calendário de ocasião** (Mães, Namorados, Noivas, Inverno): conteúdo planejado bate conteúdo improvisado.\n- **Nomear coleções**, não só produtos — "Verão Vessel", "linha X" dá história e recompra.\n\n**Veredito competitivo:** **referência de storytelling comercial.** Conversão validada, replicável e barata — alta prioridade de cópia.`,
    tags: ['#SayYes 1.019❤', 'Bambi Core (tendência própria)', 'Conteúdo de ocasião', 'SKU+preço', '140+ lojas / eyewear', 'Calendário de ocasião', 'Replicável'] },
},
'Luz da Lua': {
  com: { t: 'A Diana e o monograma LL: o poder de uma peça-ícone recorrente',
    r: `A Luz da Lua tem algo que vale ouro no varejo de bolsa e que a maioria das concorrentes não tem: **uma peça-âncora com nome próprio que volta toda estação**. Chama-se **Diana** — e é uma aula de desenvolvimento.\n\n## O que as campeãs revelam\nTicket **intermediário (R$500 a R$1.500)**, monograma **LL Mocca** onipresente e a **Diana** em várias encarnações:\n- **Executiva Grande Monograma** — R$1.499,90 *(topo)*\n- **Kiara Bucket Grande** — R$1.359,90\n- **Bella Tiracolo Média** — R$1.199,90\n- **Diana Tote Pequena** (Atacama / Croco) — R$999,90\n- **Tiracolo Pequena Monograma** — R$499,90 *(entrada)*\n\nO segredo: a marca **não precisa lançar mil novidades** — ela **reedita a Diana** em novas cores, tamanhos e materiais, e o cliente volta para colecionar a "próxima Diana".\n\n## As novidades elevam o teto\nA leva nova vai a **R$2.499,90** (Clutch Madras) e estreia a **Clothing Collection** — 4 jaquetas de couro (Lille, Pollina, Siena Suede, Dallas, com Sofia Resing). A marca **cruzou a fronteira da categoria**: de bolsas/calçados para **vestuário em couro**, ampliando o share de carteira da mesma cliente.\n\n## Onde isso se encaixa no tabuleiro\nIntermediário (R$500–1.500), sobreposto à Jorge Bischoff. Para a Vessel, mais que concorrente de preço, é o **melhor case de "peça-ícone" do painel inteiro** — a prova viva de que um nome forte vale mais que um catálogo cheio.\n\n## Movimento recomendado p/ Vessel\n- **A lição nº 1 de todo o relatório: ter a sua Diana.** Eleger uma bolsa, dar nome, reeditar em novas cores/materiais a cada estação. Reconhecimento e recompra que lançamento avulso nunca entrega.\n- **Construir família em torno do ícone** (mini, tote, baguete da mesma "Diana"): vira sistema, não item.\n- **Estudar a expansão de categoria** com cautela — só faz sentido depois que o ícone de bolsa estiver consolidado.\n\n**Veredito competitivo:** **o melhor professor de desenvolvimento do painel.** Menos ameaça, mais manual de como construir desejo recorrente.`,
    tags: ['Diana (peça-ícone)', 'Monograma LL', 'R$500–1.500', 'Topo até R$2.499', 'Clothing Collection', 'Reedita, não inventa', 'Tenha a sua Diana'] },
  mkt: { t: 'Produto-cêntrico e consistente: a dupla bolsa + calçado que engaja sempre',
    r: `A Luz da Lua não tenta inventar moda no feed — ela **vende o que tem, com método** — e a consistência é justamente o que faz funcionar.\n\n## A mecânica\nConteúdo **produto-cêntrico e bem resolvido**: combinações **bolsa + calçado** com **códigos na legenda**, texturas nobres em destaque (**couro Alligator**) e um guarda-chuva afetivo (*"Conexões que Marcam"*, Namorados). A **Diana** lidera também no digital — é ícone de **produto E de conteúdo**, o que multiplica o retorno de cada post.\n\n## O que viralizou\n- **Diana** + slingback — **1.068❤** *(líder)*\n- Couro **Alligator** + bota — **630❤**\n- Slingback + bolsa c/ correntes — **593❤**\n- Tote off-white Panna + Alligator — **562❤**\n\nNão há "post fora da curva" — há **consistência alta**. A marca provou que **estabilidade vale mais que um viral isolado**: previsibilidade de engajamento é previsibilidade de venda.\n\n## O bastidor estratégico\nEstreia da **Clothing Collection** com a modelo internacional **Sofia Resing** — a comunicação acompanha a expansão de categoria, levando a mesma cliente a comprar mais itens da marca.\n\n## Movimento recomendado p/ Vessel\n- **Adotar a tríade vencedora** (que se repete em Santa Lolla, JB e aqui): **ícone recorrente + dupla bolsa/calçado + código de produto**. É o consenso do que engaja.\n- **Trocar "viral" por "consistência":** não é preciso reinventar o conteúdo toda semana — é preciso ser fiel a um ícone e a um formato que funcionam.\n- **Apoiar o conteúdo no ícone** (a "Diana da Vessel"): cada post do ícone rende mais que um post de produto anônimo.\n\n**Veredito competitivo:** **modelo de disciplina de conteúdo.** Baixo risco, alto retorno — o tipo de marketing que a Vessel consegue executar bem.`,
    tags: ['Diana 1.068❤', 'Bolsa + calçado', 'Couro Alligator', 'Código no post', 'Consistência > viral', 'Ícone no conteúdo', 'Baixo risco'] },
},
'Petite Jolie': {
  com: { t: 'PVC injetado e mini bags: o produto de entrada que amadurece a paleta',
    r: `A Petite Jolie é o **piso de preço** do painel — e desenvolve produto com a lógica de **acessório pop, afetivo e colecionável**, não de bolsa "séria".\n\n## O que as campeãs revelam\nFaixa **R$64,90 a R$269,90**, base **sintética/injetada (PVC)**, shapes pequenos e divertidos:\n- **May** — R$269,99 *(topo)*\n- **Fluffy Bag** — R$249,99\n- **Moon** — R$229,99\n- **Love II / Debby / Shape III** — R$169–179,99\n- **Becky** — R$64,99 *(o piso absoluto do painel)*\n\nO PVC injetado é a decisão-mãe: **barato de produzir, fácil de colorir, leve, lavável** — perfeito para girar cor e collab rápido.\n\n## As novidades mostram a virada\nA leva nova **abandona o flúor festivo** por uma **paleta terrosa** (preto, chocolate, doce de leite, creme) e investe em **mini bags** (Mini Paris, Texas). É uma marca de praia/festa **amadurecendo para o dia a dia** — movimento clássico de quem quer aumentar frequência de uso e ticket sem trocar de público.\n\n## Onde isso se encaixa no tabuleiro\n**Abaixo de todo mundo** (R$65–270), inclusive da Vessel. Não é concorrente de preço — é **caso de estudo de reposicionamento barato**: como uma marca de entrada **sobe percepção sem subir custo**, usando **cor e collab** como alavancas.\n\n## Movimento recomendado p/ Vessel\n- **Estudar a maturação de paleta:** a mudança do flúor para o terroso é exatamente como se "envelhece" uma marca de entrada para o uso diário. Cor é a alavanca de reposicionamento **mais barata que existe**.\n- **Considerar uma linha-isca afetiva/colecionável** (mini bag, charm, collab leve) para capturar a cliente jovem que começa na PJ e pode subir para a Vessel.\n- **Não desprezar o piso:** quem fideliza no R$65 hoje é quem paga R$250 amanhã. A PJ está formando o cliente que a Vessel quer no futuro.\n\n**Veredito competitivo:** **não é ameaça, é viveiro.** Forma o cliente de entrada — vale observar para herdá-lo.`,
    tags: ['R$65–270 (piso)', 'PVC injetado', 'Mini bags', 'Paleta terrosa (maturação)', 'Collab Hello Kitty', 'Cor = alavanca barata', 'Viveiro de cliente'] },
  mkt: { t: 'Afeto, parcela e bundle: o feed mais descaradamente comercial (e funciona)',
    r: `Se a Carmen Steffens é desejo sem CTA, a Petite Jolie é o **extremo oposto da régua** — venda explícita, sem pudor — e os números **aprovam o método**.\n\n## A mecânica\nCada post traz **preço, parcelamento (até 10x) e bundle** (bolsa + tênis + copo) com tom **afetivo e popular** ("diva", "amiga"), forte uso de **influenciadoras** (Stuchi) e **datas comerciais** (Mães, Namorados). É varejo puro, e a audiência **não recua diante da oferta — responde a ela**.\n\n## O que viralizou\n- Dia das Mães com influencers — **694❤ / 31💬** *(líder)*\n- Bolsa **Secret** (praticidade) — **417❤**\n- Amalfi + Puff Sneaker — **292❤**\n- "Jeitinho brasileiro de se apaixonar" (Namorados) — **262❤**\n\nO aprendizado destrói um mito caro: **preço e parcela no post não espantam — destravam**. Quando o público é popular, **clareza de oferta é conteúdo de valor**.\n\n## O bastidor estratégico\nDo grupo **Aniger**, a marca anunciou **250 lojas franqueadas em 5 anos** (de 40+): a sandália de plástico virou **tese de franchising** e varejo capilarizado. O marketing afetivo sustenta a expansão dando à franquia um **conceito de marca pronto**.\n\n## Movimento recomendado p/ Vessel\n- **Adotar o mecanismo, adaptar o tom:** **clareza de oferta** (preço + parcela + "como comprar") sem necessariamente o tom popular. Dá para ser sofisticada **e** explícita na compra.\n- **Mirar o ponto ideal:** sofisticação da Carmen Steffens **+** clareza da Petite Jolie = desejo com caminho de compra. É a síntese que nenhuma concorrente está fazendo.\n- **Usar bundle estratégico** (bolsa + acessório) para subir ticket médio sem desconto.\n\n**Veredito competitivo:** **mestre do mecanismo de conversão.** O tom não serve à Vessel, mas a engenharia de oferta, sim.`,
    tags: ['Preço + 10x no post', 'Bundles', 'Influencers (Stuchi)', 'Datas comerciais', '250 lojas / franquia', 'Clareza destrava', 'Ponto ideal CS+PJ'] },
},
'Santa Lolla': {
  com: { t: 'A concorrente-espelho: sintético acessível com uma máquina de fabricar ícone',
    r: `Esta é **a marca mais parecida com a Vessel** no painel inteiro — mesmo terreno, mesmo cliente, mesmo ticket. Estudar a Santa Lolla é estudar **o próprio campo de batalha**.\n\n## O que as campeãs revelam\nShoppers e baguetes em **sintético** ("floater"/"soft"), faixa **R$149,90 a R$299,90**, dominando **alça de ombro e corrente** em preto/marrom/vanilla:\n- **Shopper Grande Nylon Noir** — R$299,90 *(topo)*\n- **Shopper Floater** (preta / safari) — R$249,90\n- **Baguete Média Soft** — R$229,90\n- **Carteira Soft c/ Corrente** — R$149,90 *(entrada)*\n\nÉ **volume, dia a dia, pouco couro** — exatamente o ringue da Vessel. A diferença não está no produto: está na **camada de marca** por cima dele.\n\n## A jogada de produto\nA linha **Lolla Icons** coroou a **Bolsa Lolli** como **ícone permanente** — lógica deliberadamente **anti-tendência**: a peça volta a cada estação em novas cores, virando totem. As novidades **Summer** trazem metalizados (dourado, snake), mochila matelassê e bolsas "na caixa". A SL faz o sintético **parecer curadoria**, não commodity.\n\n## Onde isso se encaixa no tabuleiro\n**Lado a lado com a Vessel** (R$150–300). Não há diferença de bolso — há diferença de **percepção**. A SL provou que, no mesmo sintético e mesmo preço, **quem constrói ícone cobra atenção e fidelidade que o concorrente sem ícone não tem**.\n\n## Movimento recomendado p/ Vessel\n- **Atacar em duas frentes:** (1) **subir material/percepção** ligeiramente acima do sintético padrão dela (onde dá para diferenciar de fato) e (2) **copiar e superar a tese Lolla Icons**.\n- **Eleger o ícone da Vessel já:** escolher uma bolsa com shape reconhecível, dar nome e reeditar com disciplina anti-tendência. Sem ícone, a Vessel é commodity ao lado de uma SL que não é.\n- **Benchmark de preço/cor toda rodada:** por ser espelho, cada movimento da SL é um teste A/B de graça para a Vessel.\n\n**Veredito competitivo:** **espelho e alvo principal.** A briga mais importante do painel — e a mais vencível, se a Vessel construir marca sobre o produto.`,
    tags: ['R$149–299', 'Sintético floater/soft', 'Bolsa Lolli (ícone)', 'Anti-tendência', 'Metalizados (Summer)', 'Espelho + alvo', 'Mais vencível'] },
  mkt: { t: 'Campeã absoluta de engajamento: a construção de "IT-bag" feita à perfeição',
    r: `A Santa Lolla **lidera o engajamento de TODO o painel** — e não por sorte. Ela opera uma **máquina de fabricar ícone**, e o melhor: a máquina é **replicável** por quem entender a peça.\n\n## A mecânica\nO vocabulário é deliberado e repetido: **"IT-BAG", "NEW ICON", #LollaIcons**. Cada post pega **um shape reconhecível**, dá **nome + código + preço**, e o repete até virar referência cultural. É **construção de ícone em tempo real, na frente do público** — o cliente assiste a bolsa "virar ícone" e quer fazer parte disso.\n\n## O que viralizou\n- **Bolsa Lolli** "novo Lolla Icon" — **2.093❤** *(o topo absoluto do painel inteiro)*\n- SL bag de **veludo** — **1.309❤**\n- SL **handbags** coloridas — **1.039❤**\n- Bolsa Lolli (pronúncia "Lôli") — **912❤**\n\nO insight que vale o relatório: **o que mais engaja não é o mais caro nem o mais novo — é o mais ICÔNICO.** A SL prova que repetir e batizar bate lançar e variar.\n\n## O bastidor estratégico\n**Rafa Kalimann** estrela "**Cápsula do Tempo**" (Dia das Mães) — narrativa emocional, três drops de estética distinta. A marca casa **ícone de produto** com **embaixadora afetiva**, cobrindo desejo e emoção.\n\n## Movimento recomendado p/ Vessel\n- **Executar o playbook completo:** eleger um ícone, dar **nome/código/preço**, e repeti-lo com convicção por estações. É o método de maior retorno de marketing do painel.\n- **Mostrar o ícone "virando ícone":** transformar a construção em conteúdo (bastidor, "por que é especial", numeração de drops).\n- **Casar ícone + ocasião** (como SL faz com Rafa/Mães): produto recorrente ancorado em momento emocional.\n\n**Veredito competitivo:** **a referência nº 1 de marketing do painel.** A pergunta que define a semana da Vessel: **qual é a nossa Lolli?**`,
    tags: ['Lolli 2.093❤ (topo absoluto)', 'IT-bag / NEW ICON', '#LollaIcons', 'Nome+código+preço', 'Rafa Kalimann', 'Icônico > novo/caro', 'Qual é a nossa Lolli?'] },
},
'Schutz': {
  com: { t: 'Hobo, Lilibet e Vanity: ícones de couro no topo da gama',
    r: `A Schutz desenvolve no **andar de cima** (R$990 a R$1.990) e organiza o portfólio com uma disciplina rara: **tudo gira em torno de ícones nomeados**.\n\n## O que as campeãs revelam\nCouro, **hobo** como shape-rei, e nomes que se repetem (**Lilibet, Agnes, Vanity**):\n- **Hobo Lilibet Fur** — R$1.990 *(topo)*\n- **Tiracolo Lilibet** (ráfia / camurça / couro) — R$1.790–1.890\n- **Satchel Vanity** (preta / verde) — R$1.390\n- **Hobo Agnes Couro** — R$990 *(entrada do premium)*\n\nO detalhe genial: a família **Lilibet** sozinha cobre vários materiais (fur, ráfia, camurça, couro) — **um nome, muitas peles**. A marca multiplica SKUs sem diluir reconhecimento, porque tudo carrega o mesmo nome-âncora.\n\n## A aposta de desenvolvimento\n**Ícones com nome próprio** (Lilibet, Vanity, Agnes) trabalhados em variações de material — exatamente a tese da Luz da Lua (Diana) e da Santa Lolla (Lolli), só que **executada no premium**. A marca ainda rejuvenesce o produto com **sapatilhas Tabi** (linha Schutzies).\n\n## Onde isso se encaixa no tabuleiro\n**Topo do painel** (junto com Carmen Steffens), 3–6× o ticket da Vessel. Não é concorrente de preço — é a **terceira prova consecutiva** (com LL e SL) de que **ícone nomeado vence catálogo anônimo em qualquer faixa**.\n\n## Movimento recomendado p/ Vessel\n- **Absorver o consenso do painel:** três marcas vencedoras, três tickets diferentes, **mesma regra** — produto com nome bate produto sem nome. A Vessel não pode ser a exceção anônima.\n- **Adotar "um nome, muitas peles":** criar o ícone e variá-lo em materiais/cores em vez de lançar shapes novos a cada estação. Menos custo de desenvolvimento, mais reconhecimento.\n- **Usar a Schutz como teto de aspiração:** mostrar que a Vessel entrega "a vibe Schutz" (ícone, atitude) por uma fração do preço.\n\n**Veredito competitivo:** **não é ameaça de bolso, é confirmação de método.** O terceiro carimbo na regra do ícone nomeado.`,
    tags: ['R$990–1.990', 'Hobo shape-rei', 'Lilibet / Vanity / Agnes', 'Um nome, muitas peles', 'Sapatilhas Tabi', 'Ícone vence catálogo', 'Confirmação de método'] },
  mkt: { t: 'Cool, anglófono e movido a comunidade: "Shop yours, Schutzies"',
    r: `A Schutz não vende bolsa — vende **pertencimento**. E a jogada mais inteligente dela é ter dado **nome ao próprio público**: os "Schutzies".\n\n## A mecânica\nConteúdo **cool e aspiracional**, com **inglês como código de status** ("Shop yours", "soft textures, cool attitude") e o **ícone no centro** (Hobo **Lilibet Fur**, **Vanity**), amarrado a influenciadoras de alto alcance. O tom é menos "compre" e mais "**faça parte**" — e pertencimento é o ativo de marca mais difícil de copiar com preço.\n\n## O que viralizou\n- **Antonela Braga** "Schutzie era" — **1.611❤** *(líder)*\n- **Lilibet Fur** + Mule Maple — **562❤**\n- Bolsa **Vanity** "da temporada" — **438❤**\n- Lilibet Fur "soft textures" — **399❤**\n\n## A estratégia de marca\nDuas campanhas (**Isa Scherer / Leoness** e **Bianca Andrade / Born to Stand Out**, dir. Rafaella Furlanetto) e, acima de tudo, o projeto **Schutzies**: plataforma para a **Geração Z** com **Antonela Braga (17 anos, 13 mi de seguidores)**. O norte é **rejuvenescer a base sem perder ticket** — atacar o futuro sem abandonar o presente.\n\n## Onde está a vantagem (difícil de copiar)\nA Schutz construiu **comunidade**, não só catálogo. Tribo com nome gera identidade, repost orgânico e fidelidade que o desconto não compra.\n\n## Movimento recomendado p/ Vessel\n- **Dar nome à tribo:** uma marca que nomeia seu público ("as [Vessel]...") cria pertencimento **de graça**. É a tática premium mais barata do painel.\n- **Adotar o "faça parte" em vez do "compre":** equilibrar os posts de oferta (Capodarte/PJ) com posts de identidade (Schutz).\n- **Mirar a Gen Z com ícone acessível:** a Schutz usa sapatilha Tabi para rejuvenescer; a Vessel pode usar um ícone de entrada para o mesmo fim.\n\n**Veredito competitivo:** **construtora de comunidade** — a vantagem mais defensável do painel. Copiável só em parte: dar nome à tribo é o começo.`,
    tags: ['Antonela 1.611❤', 'Inglês = status', 'Lilibet/Vanity ícones', 'Schutzies (Gen Z)', 'Comunidade > catálogo', 'Nomeie sua tribo', 'Vantagem defensável'] },
},
};

const cats = { com: 'Resumo Comercial', mkt: 'Resumo Marketing' };
const rows = [];
for (const [marca, o] of Object.entries(S)) {
  for (const k of ['com', 'mkt']) {
    rows.push({
      marca, categoria: cats[k], titulo: o[k].t, resumo: o[k].r,
      url: null, fonte: 'RBV · Observatório · síntese estratégica do módulo', data_publicacao: RODADA, rodada: RODADA,
      destaque: false, imagem_url: null, produtos: (o[k].tags || []).map(t => ({ nome: t })),
    });
  }
}

for (const c of Object.values(cats)) {
  await rest('DELETE', `noticias_concorrentes?rodada=eq.${RODADA}&categoria=eq.${encodeURIComponent(c)}`);
}
let ok = 0;
try { ok = (await rest('POST', 'noticias_concorrentes', rows)).length; }
catch (e) {
  console.log('bulk falhou, 1 a 1:', String(e).slice(0, 120));
  for (const row of rows) { try { await rest('POST', 'noticias_concorrentes', [row]); ok++; } catch (e2) { console.log('FALHOU', row.marca, row.categoria, String(e2).slice(0, 140)); } }
}
console.log(`Inseridos ${ok}/${rows.length} resumos de módulo (v3: estratégicos).`);
