-- docs/migrations/009_noticias_2026-06-11_rodada2.sql
-- Segunda rodada de notícias (11/06/2026): mais matérias por marca, recentes em
-- primeiro plano, ampliando temas (Marketing, Design, Moda além de
-- Estratégia/Tendência/Lançamento/Campanha/Preço/Faturamento/Expansão).
-- Rode DEPOIS da 007. Idempotente: ON CONFLICT (marca,titulo,rodada) não duplica.
-- A matéria com destaque=true (criada nesta rodada) vira a capa da marca.

INSERT INTO public.noticias_concorrentes
  (marca, titulo, resumo, categoria, url, fonte, data_publicacao, rodada, destaque)
VALUES
-- ───────── Santa Lolla ─────────
($$Santa Lolla$$,$$Inverno 2026 "A Potência do Real" com casting de 12 personagens$$,$$Campanha intimista sobre pluralidade feminina como identidade e conexão. Estética sofisticada e contemporânea; coleção já nas lojas e no site.$$,$$Campanha$$,$$https://www.faroldabahia.com.br/noticia/colecao-de-inverno-da-santa-lolla-exalta-a-pluralidade-feminina$$,$$Farol da Bahia$$,'2026-05-15','2026-06-11',true),
($$Santa Lolla$$,$$Cápsula "Torcida SL": flip flops para a Copa 2026$$,$$Surfa no clima do futebol transformando chinelos em peça-chave de torcida. Já disponível em todas as lojas físicas e no site oficial.$$,$$Lançamento$$,$$https://auroracultural.com/noticias/moda/santa-lolla-lanca-chinelos-inspirados-na-torcida-brasileira/$$,$$Aurora Cultural$$,'2026-06-01','2026-06-11',false),
($$Santa Lolla$$,$$Verão 2026 "O verão mais gostoso da sua vida" + collab gelateria$$,$$Coleção inspirada em rotinas simples de verão; parceria com a Le Botteghe di Leonardo aproxima sabores de gelato das cores e texturas das peças.$$,$$Lançamento$$,$$https://vanitybrasil.com.br/santa-lolla-lanca-preview-verao-2026-com-frescor-e-estilo/$$,$$Vanity Brasil$$,'2026-05-20','2026-06-11',false),
($$Santa Lolla$$,$$Verão 26 com shapes marcantes e referências aos anos 70$$,$$Aposta em silhuetas fortes e revival setentista para diferenciar a estética da coleção.$$,$$Moda$$,$$https://clamagazine.com/santa-lolla-lanca-nova-colecao-de-verao-26-repleta-de-shapes-marcantes-e-referencias-aos-anos-70/$$,$$CLA Magazine$$,'2026-05-10','2026-06-11',false),
($$Santa Lolla$$,$$Calendário de drops + celebridades vira motor de marketing$$,$$Ações recorrentes por data comercial (drops, Compre & Ganhe, embaixadoras como Rafa Kalimann) mantêm a marca em mídia o ano todo.$$,$$Marketing$$,$$https://abramark.com.br/destaques/santa-lolla-campanha-capsula-do-tempo-rafa-kalimann-dia-das-maes-2026/$$,$$ABRAMARK$$,'2026-04-20','2026-06-11',false),

-- ───────── Capodarte ─────────
($$Capodarte$$,$$Couros exóticos no foco: textura "enguia" e couro com pelo natural$$,$$Materiais de impacto visual e riqueza tátil no Inverno 2026; metais em cobre e ouro envelhecido dão profundidade.$$,$$Design$$,$$https://www.semanapop.com.br/capodarte-reflete-sobre-legado-na-colecao-inverno-2026/$$,$$Semana Pop$$,'2026-05-12','2026-06-11',true),
($$Capodarte$$,$$Linha Tressê Signature: trama manual e acabamento hand-painted$$,$$Edição limitada celebra os 35 anos com artesania em leitura contemporânea, exclusividade e autenticidade peça a peça.$$,$$Design$$,$$https://www.semanapop.com.br/capodarte-reflete-sobre-legado-na-colecao-inverno-2026/$$,$$Semana Pop$$,'2026-05-12','2026-06-11',false),
($$Capodarte$$,$$Paleta de neutros e terrosos com nuances rosadas$$,$$Equilíbrio entre tons sóbrios e delicados, alinhado às cores do inverno; reforça posicionamento premium e atemporal.$$,$$Moda$$,$$https://www.semanapop.com.br/capodarte-reflete-sobre-legado-na-colecao-inverno-2026/$$,$$Semana Pop$$,'2026-05-12','2026-06-11',false),

-- ───────── Carmen Steffens ─────────
($$Carmen Steffens$$,$$Convenção "Flor de Caju" lança Primavera-Verão 27$$,$$Evento de marca celebra a moda brasileira e antecipa a próxima coleção, unindo tendências globais à essência da marca.$$,$$Lançamento$$,$$https://www.dalvanamendes.com/noticias/convencao-carmen-steffens-celebra-a-forca-da-moda-brasileira-com-o-tema-flor-de-caju-e-lanca-colecao-primavera-verao-27/$$,$$Dalvana Mendes$$,'2026-04-10','2026-06-11',true),
($$Carmen Steffens$$,$$Expansão global: nova loja em Guimarães (Portugal)$$,$$Plano de internacionalização mira ainda Barcelona, Miami, Las Vegas, Melbourne e Emirados Árabes. Crescimento por presença internacional.$$,$$Expansão$$,$$https://www.dalvanamendes.com/noticias/convencao-carmen-steffens-celebra-a-forca-da-moda-brasileira-com-o-tema-flor-de-caju-e-lanca-colecao-primavera-verao-27/$$,$$Dalvana Mendes$$,'2026-04-10','2026-06-11',false),
($$Carmen Steffens$$,$$Andressa Suita é a nova embaixadora da marca$$,$$Parceria com influenciadora e ícone de estilo marca capítulo de renovação e captura de audiência.$$,$$Marketing$$,$$https://omaranhense.com/andressa-suita-estrela-campanha-da-carmen-steffens-e-revela-novidade-ao-publico-nesta-quarta-feira-27/$$,$$O Maranhense$$,'2026-03-27','2026-06-11',false),
($$Carmen Steffens$$,$$Coleção "Lumière d'Été" reposiciona a marca como mais contemporânea$$,$$Nova identidade busca leitura elegante, atemporal e contemporânea — sinal de reposicionamento estratégico.$$,$$Estratégia$$,$$https://carmensteffens.pt/$$,$$Carmen Steffens$$,'2026-04-10','2026-06-11',false),

-- ───────── Dumond ─────────
($$Dumond$$,$$Posicionamento: couro legítimo, conforto premium e bolsas modernas$$,$$Mix de salto, sandália, tênis e bolsas com design exclusivo; aposta em elegância + conforto como diferencial.$$,$$Moda$$,$$https://www.dumond.com.br/$$,$$Dumond$$,'2026-06-01','2026-06-11',true),
($$Dumond$$,$$Promoção: 10% OFF na 1ª compra + Sale até 50% OFF$$,$$Captura por primeira compra e outlet agressivo seguem como motor de conversão no e-commerce.$$,$$Preço/Promo$$,$$https://www.cuponation.com.br/cupom-desconto-dumond$$,$$Cuponation$$,'2026-06-01','2026-06-11',false),

-- ───────── Chenson ─────────
($$Chenson$$,$$30 anos: líder em bolsas femininas no atacado do Brasil$$,$$Escala de atacado e preço acessível como fosso competitivo; +20 anos acompanhando a "mulher moderna" com design atual.$$,$$Estratégia$$,$$https://chenson.com.br/$$,$$Chenson$$,'2026-02-01','2026-06-11',true),
($$Chenson$$,$$Coleção DUO com 300+ produtos por coleção$$,$$Volume e variedade altíssimos por drop, sustentando giro e presença em marketplaces.$$,$$Lançamento$$,$$https://www.lojachenson.com.br/novidades$$,$$Loja Chenson$$,'2026-05-01','2026-06-11',false),
($$Chenson$$,$$Modelos "Hobo Chic", "Soft Ombro" e "New Matelassê II"$$,$$Linha atual e acessível seguindo formatos em alta (hobo/ombro) com leitura comercial.$$,$$Moda$$,$$https://www.lojachenson.com.br/novidades$$,$$Loja Chenson$$,'2026-05-01','2026-06-11',false),

-- ───────── SAAD ─────────
($$SAAD$$,$$Inverno 2026: bolsas de tecido com acabamento em couro legítimo$$,$$De pequenas a grandes, unindo funcionalidade, elegância e modernidade; foco em sofisticação.$$,$$Lançamento$$,$$https://www.saadbolsa.com.br/bolsas$$,$$SAAD$$,'2026-05-05','2026-06-11',true),
($$SAAD$$,$$50 anos: ateliê próprio, 100% manual, ferragens personalizadas$$,$$Banho exclusivo e camada de verniz nas peças; diferencial artesanal/luxo nacional como território.$$,$$Design$$,$$https://www.saadbolsa.com.br/$$,$$SAAD$$,'2026-02-01','2026-06-11',false),
($$SAAD$$,$$Posicionamento de luxo nacional "feito à mão, sem máquinas digitais"$$,$$Narrativa de exclusividade e cuidado artesanal sustenta preço premium e desejo de marca.$$,$$Estratégia$$,$$https://www.instagram.com/saadbolsaoficial/$$,$$Instagram$$,'2026-05-05','2026-06-11',false),

-- ───────── Arezzo&Co / Azzas 2154 ─────────
($$Arezzo&Co$$,$$Azzas 2154 lucra R$770,7 mi em 2025 (+30,5%), 1º ano pós-fusão$$,$$Primeiro ano completo da combinação Arezzo&Co + Grupo Soma fecha com lucro recorde e crescimento de dois dígitos.$$,$$Faturamento$$,$$https://economicnewsbrasil.com.br/2026/03/12/lucro-da-azzas-2154/$$,$$Economic News Brasil$$,'2026-03-12','2026-06-11',true),
($$Arezzo&Co$$,$$1T26: lucro recorrente cai 45,7% (R$63,9 mi); receita -8%$$,$$Queda puxada por ajuste de estoques (sell-in fraco) enquanto reequilibra rede x venda ao consumidor (sell-out).$$,$$Faturamento$$,$$https://www.infomoney.com.br/mercados/azzas-2154-azza3-resultados-primeiro-trimestre-2026/$$,$$InfoMoney$$,'2026-05-08','2026-06-11',false),
($$Arezzo&Co$$,$$Crise societária: possível cisão entre Birman e Jatahy$$,$$Desenho de separação pode criar até três empresas derivadas da Azzas; JP Morgan acende alerta de governança.$$,$$Estratégia$$,$$https://www.seudinheiro.com/2026/empresas/azzas-2154-azza3-acoes-saltam-com-possivel-cisao-entre-jatahy-e-birman-jp-morgan-acende-alerta-para-governanca-lvgb/$$,$$Seu Dinheiro$$,'2026-05-20','2026-06-11',false),
($$Arezzo&Co$$,$$Nove executivos-chave deixaram a Azzas; saída de Ruy Kameyama$$,$$Turnover no alto escalão (mais recente: líder de Fashion & Lifestyle) sinaliza reorganização e instabilidade.$$,$$Estratégia$$,$$https://www.seudinheiro.com/2026/empresas/sai-um-entram-dois-azzas-2154-azza3-reorganiza-a-casa-apos-baixas-no-alto-escalao-veja-como-fica-agora-bdap/$$,$$Seu Dinheiro$$,'2026-04-01','2026-06-11',false),
($$Arezzo&Co$$,$$Capex -30,8% (R$383,7 mi): disciplina de capital$$,$$Corte de investimento e foco em caixa em ano de receita mais fraca; prioridade a margem e estoque saudável.$$,$$Estratégia$$,$$https://www.infomoney.com.br/mercados/azzas-2154-azza3-resultados-primeiro-trimestre-2026/$$,$$InfoMoney$$,'2026-05-08','2026-06-11',false),

-- ───────── La Vessel (homônima) ─────────
($$La Vessel$$,$$Monitorar @lavessel: reforçar autoridade de "Vessel" em buscas$$,$$Concorrente homônima segue ativa; ação contínua de SEO/social para que "Vessel bolsas" leve a @vessel.brasil.$$,$$Marketing$$,$$https://www.instagram.com/lavessel/$$,$$Instagram$$,'2026-06-05','2026-06-11',true),

-- ───────── Mercado / Tendências / Design / Moda ─────────
($$Mercado$$,$$Bolsas 2026: tote, baguete e tiracolo dominam; slouchy e correntes em alta$$,$$Formatos versáteis dia-a-noite lideram; animal print, modelos com corrente aparente e palha/crochê refinados ganham espaço.$$,$$Tendência$$,$$https://www.em.com.br/emfoco/2026/03/12/as-4-bolsas-que-vao-dominar-as-ruas-em-2026-e-transformar-qualquer-visual-basico/$$,$$Estado de Minas$$,'2026-03-12','2026-06-11',true),
($$Mercado$$,$$Marrom é a cor do ano nos acessórios (chocolate → caramelo)$$,$$Tom assume protagonismo ao lado de neutros atemporais (bege, off-white, preto) e sofisticados (vinho, marinho, verde musgo, nudes).$$,$$Moda$$,$$https://www.vitallycebags.com.br/blog/tendencias-em-bolsas-femininas-2025-2026/$$,$$Vitallyce Bags$$,'2026-04-01','2026-06-11',false),
($$Mercado$$,$$WGSN/Pantone Inverno 2026: rosa otimista, vermelho de impacto, azul elétrico$$,$$Paleta da estação combina Cloud Dancer (neutro claro), azul-marinho clássico e laranja vibrante para PDV.$$,$$Design$$,$$https://feiradamodainverno.com.br/cores-tendencia-2026-o-que-a-wgsn-brasil-aponta-para-o-proximo-ano-da-moda/$$,$$FEIMI / WGSN$$,'2026-02-15','2026-06-11',false),
($$Mercado$$,$$Técnicas da estação: pelos, laser cut e tressê$$,$$Três frentes de construção definem o inverno 2026 e devem aparecer em acessórios e calçados premium.$$,$$Design$$,$$https://crespi.com.br/tendencias-de-cores-outono-inverno-2026-redefinem-a-moda/$$,$$Crespi do Brasil$$,'2026-03-01','2026-06-11',false),
($$Mercado$$,$$Acessórios do inverno: cintos protagonistas, lenços, chapéus e óculos oversized$$,$$Foco no pescoço e na silhueta; sobreposição de colares e bolsas espaçosas completam o look da estação.$$,$$Tendência$$,$$https://stealthelook.com.br/acessorios-tendencia-do-inverno-2026-5-itens-que-nao-podem-faltar-no-look/$$,$$Steal The Look$$,'2026-03-15','2026-06-11',false),
($$Mercado$$,$$Calçados: flats rente ao chão e retorno do anabela; conforto domina$$,$$Solado macio, palmilhas confortáveis e design ergonômico nas prateleiras; tênis casual e sandália anatômica em alta.$$,$$Tendência$$,$$https://doutorvarejo.com/sapatos-da-moda-conheca-as-tendencias-para-2026/$$,$$Doutor Varejo$$,'2026-03-05','2026-06-11',false),
($$Mercado$$,$$Varejo de moda 2026: vestuário R$314,9 bi (+6,8%), calçados R$81,5 bi (+6,1%)$$,$$Crescimento puxado por preço médio; faturamento avança mais que volume em meio a incerteza econômica.$$,$$Faturamento$$,$$https://gbljeans.com.br/mercado/economia/vestuario-e-calcados-somam-r-396-bilhoes-em-2025/$$,$$GBL Jeans / IEMI$$,'2026-05-01','2026-06-11',false),
($$Mercado$$,$$Inverno 2026 (mai–ago): 1,85 bi de peças, crescimento moderado$$,$$IEMI projeta avanço mais expressivo em faturamento que em unidades; temporada cautelosa porém positiva.$$,$$Faturamento$$,$$https://iemi.com.br/varejo-de-moda-estimativa-moderada-para-o-inverno-2026/$$,$$IEMI$$,'2026-05-01','2026-06-11',false),
($$Mercado$$,$$66% preferem comprar moda online: e-commerce no centro da jornada$$,$$Predominância digital reforça captura por newsletter/app, conteúdo em vídeo curto e omnichannel.$$,$$Marketing$$,$$https://edrone.me/br/blog/ecommerces-de-moda$$,$$edrone$$,'2026-02-01','2026-06-11',false),
($$Mercado$$,$$Promo como norma: tendência chega via outlet pra testar aceitação$$,$$Setor segue em modo promocional; descontos pesados em marketplaces pressionam margem — evitar guerra de desconto raso.$$,$$Preço/Promo$$,$$https://doutorvarejo.com/sapatos-da-moda-conheca-as-tendencias-para-2026/$$,$$Doutor Varejo$$,'2026-03-05','2026-06-11',false)

ON CONFLICT (marca, titulo, rodada) DO NOTHING;
